- name: create user
  tags: always
  ansible.builtin.user:
    name: ghost
    groups: root 

- name: add sudoers file for ghost
  tags: always
  ansible.builtin.copy:
    src: sudoer_ghost
    dest: /etc/sudoers.d/ghost
    owner: root
    group: root
    mode: 0440

- name: add ssh key for ghost user
  tags: always
  ansible.builtin.authorized_key:
    user: ghost
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYHOG4EEhHd+vBkvV+BcRWUEyqcRgBwjsKOCVWyIt/r benise@ubuntu-ws"
